/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/sbicmn"
	"lite5gc/openapi/models"
	udmhdl "lite5gc/udm/sbi/handler"
	"net/http"
)

// RegistrationAmf3gppAccess - register as AMF for 3GPP access
func RegistrationAmf3gppAccess(c *gin.Context) {
	var amf3GppAccessRegistration models.Amf3GppAccessRegistration
	if err := c.ShouldBindJSON(&amf3GppAccessRegistration); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := sbicmn.NewRequest(c.Request, amf3GppAccessRegistration)
	req.Params["ueId"] = c.Param("ueId")
	HTTPResponse := udmhdl.HandleRegistrationAmf3gppAccess(req)
	c.Header("Location", HTTPResponse.Header.Get("Location"))
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	return
}
