/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/sbicmn"
	udmhdl "lite5gc/udm/sbi/handler"
)

// GetAmf3gppAccess - retrieve the AMF registration for 3GPP access information
func GetAmf3gppAccess(c *gin.Context) {
	req := sbicmn.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Param("ueId")
	req.Query.Add("supported-features", c.Query("supported-features"))

	//handlerMsg := udm_message.NewHandlerMessage(udm_message.EventGetAmf3gppAccess, req)
	//udm_handler.SendMessage(handlerMsg)
	//rsp := <-handlerMsg.ResponseChan

	HTTPResponse := udmhdl.HandleRetrievalAmf3gppAccessReg(req)
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)

	return
}
