/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/sbicmn"
	"lite5gc/udm/sbi/handler"
)

// DeregistrationSmfRegistrations - delete an SMF registration
func DeregistrationSmfRegistrations(c *gin.Context) {
	req := sbicmn.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Params.ByName("ueId")
	req.Params["pduSessionId"] = c.Params.ByName("pduSessionId")

	//handlerMsg := udm_message.NewHandlerMessage(udm_message.EventDeregistrationSmfRegistrations, req)
	//udm_handler.SendMessage(handlerMsg)
	//rsp := <-handlerMsg.ResponseChan

	HTTPResponse := udmhdl.HandleDregistrationSmf(req)
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
