/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	// "fmt"
	"github.com/gin-gonic/gin"
)

// UpdateAmf3gppAccess - Update a parameter in the AMF registration for 3GPP access
func UpdateAmf3gppAccess(c *gin.Context) {
	//var amf3GppAccessRegistrationModification models.Amf3GppAccessRegistrationModification
	//if err := c.ShouldBindJSON(&amf3GppAccessRegistrationModification); err != nil {
	//	rlogger.UecmLog.Errorln(err)
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := models.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//
	//req := sbicmn.NewRequest(c.Request, amf3GppAccessRegistrationModification)
	//req.Params["ueId"] = c.Param("ueId")
	//
	//handlerMsg := udm_message.NewHandlerMessage(udm_message.EventUpdateAmf3gppAccess, req)
	//udm_handler.SendMessage(handlerMsg)
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	return
}
