/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/sbicmn"
	"lite5gc/openapi/http_wrapper"
)

// GetAmfNon3gppAccess - retrieve the AMF registration for non-3GPP access information
func GetAmfNon3gppAccess(c *gin.Context) {

	req := sbicmn.NewRequest(c.Request, nil)
	req.Params["ueId"] = c.Param("ueId")
	req.Query.Add("supported-features", c.Query("supported-features"))

	HTTPResponse := http_wrapper.Response{}
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	return
}
