/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	"github.com/gin-gonic/gin"
)

// UpdateAmfNon3gppAccess - update a parameter in the AMF registration for non-3GPP access
func UpdateAmfNon3gppAccess(c *gin.Context) {
	//var amfNon3GppAccessRegistrationModification models.AmfNon3GppAccessRegistrationModification
	//if err := c.ShouldBindJSON(&amfNon3GppAccessRegistrationModification); err != nil {
	//	rlogger.UeauLog.Errorln(err)
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := models.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//
	//req := sbicmn.NewRequest(c.Request, amfNon3GppAccessRegistrationModification)
	//req.Params["ueId"] = c.Param("ueId")
	//
	//handlerMsg := udm_message.NewHandlerMessage(udm_message.EventUpdateAmfNon3gppAccess, req)
	//udm_handler.SendMessage(handlerMsg)
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	return
}
