/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/sbicmn"
	"lite5gc/openapi/models"
	udmhdl "lite5gc/udm/sbi/handler"
	"net/http"
)

// RegistrationSmfRegistrations - register as SMF
func RetrievalSmfRegistrations(c *gin.Context) {
	var smfReg models.SmfRegistration
	if err := c.ShouldBindJSON(&smfReg); err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := sbicmn.NewRequest(c.Request, smfReg)
	req.Params["ueId"] = c.Params.ByName("ueId")

	//req.Params["pduSessionId"] = c.Params.ByName("pduSessionId")
	//handlerMsg := udm_message.NewHandlerMessage(udm_message.EventDeregistrationSmfRegistrations, req)
	//udm_handler.SendMessage(handlerMsg)
	//rsp := <-handlerMsg.ResponseChan

	HTTPResponse := udmhdl.HandleRetrievalSmf(req)
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
