/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Communication

import (
	"github.com/gin-gonic/gin"
)

// N1N2MessageUnSubscribe - Namf_Communication N1N2 Message UnSubscribe (UE Specific) service Operation
func N1N2MessageUnSubscribe(c *gin.Context) {

	//req := sbicmn.NewRequest(c.Request, nil)
	//req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	//req.Params["subscriptionId"] = c.Params.ByName("subscriptionId")
	//
	//handlerMsg := amf_message.NewHandlerMessage(amf_message.EventN1N2MessageUnSubscribe, req)
	//amf_message.SendMessage(handlerMsg)
	//
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//
	//c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
