/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Communication

import (
	"github.com/gin-gonic/gin"
)

// CreateUEContext - Namf_Communication CreateUEContext service Operation
func CreateUEContext(c *gin.Context) {
	//var request namf_comm.CreateUeContextRequest
	//request.JsonData = new(namf_comm.UeContextCreateData)
	//s := strings.Split(c.GetHeader("Content-Type"), ";")
	//var err error
	//switch s[0] {
	//case "application/json":
	//	err = c.ShouldBindJSON(request.JsonData)
	//case "multipart/related":
	//	err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	//}
	//
	//if err != nil {
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := namf_comm.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	logger.CommLog.Errorln(problemDetail)
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//
	//req := sbicmn.NewRequest(c.Request, request)
	//req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	//
	//handlerMsg := amf_message.NewHandlerMessage(amf_message.EventCreateUEContext, req)
	//amf_message.SendMessage(handlerMsg)
	//
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//if HTTPResponse.Status == http.StatusCreated {
	//	c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	//} else {
	//	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	//}

}

// EBIAssignment - Namf_Communication EBI Assignment service Operation
func EBIAssignment(c *gin.Context) {
	//var request namf_comm.AssignEbiData
	//
	//err := c.ShouldBindJSON(&request)
	//if err != nil {
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := namf_comm.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	logger.CommLog.Errorln(problemDetail)
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//
	//req := sbicmn.NewRequest(c.Request, request)
	//req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	//
	//handlerMsg := amf_message.NewHandlerMessage(amf_message.EventEBIAssignment, req)
	//amf_message.SendMessage(handlerMsg)
	//
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//
	//c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}

// RegistrationStatusUpdate - Namf_Communication RegistrationStatusUpdate service Operation
func RegistrationStatusUpdate(c *gin.Context) {
	//var request namf_comm.UeRegStatusUpdateReqData
	//
	//err := c.ShouldBindJSON(&request)
	//if err != nil {
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := namf_comm.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	logger.CommLog.Errorln(problemDetail)
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//
	//req := sbicmn.NewRequest(c.Request, request)
	//req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	//
	//handlerMsg := amf_message.NewHandlerMessage(amf_message.EventRegistrationStatusUpdate, req)
	//amf_message.SendMessage(handlerMsg)
	//
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//
	//c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}

// ReleaseUEContext - Namf_Communication ReleaseUEContext service Operation
func ReleaseUEContext(c *gin.Context) {
	//var request namf_comm.UeContextRelease
	//
	//err := c.ShouldBindJSON(&request)
	//if err != nil {
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := namf_comm.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	logger.CommLog.Errorln(problemDetail)
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//
	//req := sbicmn.NewRequest(c.Request, request)
	//req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	//
	//handlerMsg := amf_message.NewHandlerMessage(amf_message.EventUEContextRelease, req)
	//amf_message.SendMessage(handlerMsg)
	//
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//
	//c.JSON(HTTPResponse.Status, HTTPResponse.Body)

}

// UEContextTransfer - Namf_Communication UEContextTransfer service Operation
func UEContextTransfer(c *gin.Context) {
	//var request namf_comm.UeContextTransferRequest
	//request.JsonData = new(namf_comm.UeContextTransferReqData)
	//s := strings.Split(c.GetHeader("Content-Type"), ";")
	//var err error
	//switch s[0] {
	//case "application/json":
	//	err = c.ShouldBindJSON(request.JsonData)
	//case "multipart/related":
	//	err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	//}
	//
	//if err != nil {
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := namf_comm.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	logger.CommLog.Errorln(problemDetail)
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//
	//req := sbicmn.NewRequest(c.Request, request)
	//req.Params["ueContextId"] = c.Params.ByName("ueContextId")
	//
	//handlerMsg := amf_message.NewHandlerMessage(amf_message.EventUEContextTransfer, req)
	//amf_message.SendMessage(handlerMsg)
	//
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//if HTTPResponse.Status == http.StatusOK {
	//	c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	//} else {
	//	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	//}
}
