/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Communication

import (
	"github.com/gin-gonic/gin"
)

// AMFStatusChangeSubscribe - Namf_Communication AMF Status Change Subscribe service Operation
func AMFStatusChangeSubscribe(c *gin.Context) {
	//var request models.SubscriptionData
	//err := c.ShouldBindJSON(&request)
	//if err != nil {
	//	problemDetail := "[Request Body] " + err.Error()
	//	rsp := models.ProblemDetails{
	//		Title:  "Malformed request syntax",
	//		Status: http.StatusBadRequest,
	//		Detail: problemDetail,
	//	}
	//	logger.CommLog.Errorln(problemDetail)
	//	c.JSON(http.StatusBadRequest, rsp)
	//	return
	//}
	//req := sbicmn.NewRequest(c.Request, request)
	//handlerMsg := amf_message.NewHandlerMessage(amf_message.EventAMFStatusChangeSubscribe, req)
	//amf_message.SendMessage(handlerMsg)
	//
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse
	//for key, val := range HTTPResponse.Header {
	//	c.Header(key, val[0])
	//}
	//c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
