/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Communication

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"lite5gc/amf/sbiamf"
	"lite5gc/cmn/rlogger"
	"lite5gc/cmn/sbicmn"
	"lite5gc/cmn/types"
	"lite5gc/openapi"
	"lite5gc/openapi/models"
	"net/http"
	"strings"
)

// N1N2MessageTransfer - Namf_Communication N1N2 Message Transfer (UE Specific) service Operation
func N1N2MessageTransfer(c *gin.Context) {
	var request models.N1N2MessageTransferRequest

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = fmt.Errorf("N1 and N2 datas are both Empty in N1N2MessgeTransfer")
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		rlogger.Trace(types.ModuleAmfSbi, rlogger.INFO, nil, problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}
	req := sbicmn.NewRequest(c.Request, request)
	req.Params["ueContextId"] = c.Params.ByName("ueContextId") //imsi-46000**********
	req.Params["reqUri"] = c.Request.RequestURI
	rlogger.Trace(types.ModuleAmfSbi, rlogger.DEBUG, nil, "req.Params[ueContextId] ", req.Params["ueContextId"])

	message := sbicmn.NewSbiHandlerMsg(sbicmn.N1N2MessageTransferReq, req)

	//set sc instance id
	message.ScInstId = 1

	//send to sc process
	sbiamf.SendScMsg(message)

	//wait for the response message here
	sbimsg, _ := message.MsgData.(*sbicmn.SbiHandlerMessage)

	rsp := <-sbimsg.ResponseChan

	rlogger.Trace(types.ModuleAmfSbi, rlogger.DEBUG, nil, "rsp(%v) ", rsp)
	HTTPResponse := rsp.HTTPResponse
	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}
	switch HTTPResponse.Status {
	case http.StatusCreated,
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusInternalServerError,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	default:
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}
}

//func N1N2MessageTransferStatus(c *gin.Context) {
//
//	req := sbicmn.NewRequest(c.Request, nil)
//	req.Params["ueContextId"] = c.Params.ByName("ueContextId")
//	req.Params["reqUri"] = c.Request.RequestURI
//	handlerMsg := amf_message.NewHandlerMessage(amf_message.EventN1N2MessageTransferStatus, req)
//	amf_message.SendMessage(handlerMsg)
//
//	rsp := <-handlerMsg.ResponseChan
//
//	HTTPResponse := rsp.HTTPResponse
//
//	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
//}
