version:
  main: "1.0"
  patch: "0.1"
logger:
  level: "debug"
  path: "log/upf.log"
  control: 1
n3:
  port id: 0
  ipv4: "192.168.4.22"
  mask: ""
n4:
  local:
    ipv4: "192.168.4.40"
    port: 8805
  smf:
    ipv4: "192.168.4.8"
    port: 8805
n6:
  port id: 0
  ipv4: "192.168.4.22"
  mask: ""
nff:
  dpdk args: "--log-level=7"
  cpu list: ""
  stats server nostats: false
  stats server address: ""
  stats server port: 0
dnn info:
  - dnn: "cmnet"
    ip: "192.168.4.200"
  - dnn: "5gnet"
    ip: "192.168.4.201"
pm:
  start module count: true
  start session count: false
