# This file is used in "Forwarding.go" example. It divides packets to four flows and drop some of them

#  Source address, Destination address, L4 protocol ID, Source port, Destination port, Output port

        ANY                 ANY              udp            ANY            ANY              1
#    111.2.0.5/32            ANY              tcp           20:29           ANY
#        ANY                 ANY              udp         3078:3964      56:61020            4
