/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pdusession

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/rlogger"
	"lite5gc/cmn/sbicmn"
	"lite5gc/cmn/types"
	"lite5gc/openapi"
	"lite5gc/openapi/models"
	"lite5gc/smf/sbismf"
	"net/http"
	"strings"
)

// PostSmContexts - Create SM Context
func PostSmContexts(c *gin.Context) {
	rlogger.FuncEntry(types.ModuleSmfSbi, nil)
	request := models.PostSmContextsRequest{JsonData: &models.SmContextCreateData{}}
	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(request.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(&request, openapi.MultipartRelatedBinding{})
	}

	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		rlogger.Trace(types.ModuleSmfSbi, rlogger.INFO, nil, problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := sbicmn.NewRequest(c.Request, &request)
	message := sbicmn.NewSbiHandlerMsg(sbicmn.PduSessCreateSMContextReq, req)
	message.ScInstId = 0 //todo
	//send to sc process
	sbismf.SendScMsg(message)

	//wait for the response message here
	sbiMsg, ok := message.MsgData.(*sbicmn.SbiHandlerMessage)
	if !ok {
		rlogger.Trace(types.ModuleSmfSbi, rlogger.ERROR, nil,
			"invalid SbiHandlerMessage type assertion")
		return
	}

	rsp := <-sbiMsg.ResponseChan
	rlogger.Trace(types.ModuleSmfSbi, rlogger.DEBUG, nil, "receive resp data from sc process")
	HTTPResponse := rsp.HTTPResponse
	for key, val := range HTTPResponse.Header {
		c.Header(key, val[0])
	}
	switch HTTPResponse.Status {
	case
		http.StatusBadRequest,
		http.StatusForbidden,
		http.StatusNotFound,
		http.StatusInternalServerError,
		http.StatusServiceUnavailable,
		http.StatusGatewayTimeout:
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	case http.StatusCreated:
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	default:
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}
}
