/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package pdusession

import (
	"lite5gc/cmn/rlogger"
	"lite5gc/cmn/sbicmn"
	"lite5gc/openapi"
	"lite5gc/openapi/models"
	"lite5gc/smf/sbismf"
	"github.com/gin-gonic/gin"
	"log"
	"net/http"
	"strings"
	"lite5gc/cmn/types"
)

// ReleaseSmContext - Release SM Context
func ReleaseSmContext(c *gin.Context) {
	rlogger.FuncEntry(types.ModuleSmfSbi, nil)

	reqData := &models.ReleaseSmContextRequest{}
	reqData.JsonData = &models.SmContextReleaseData{}
	reqData.JsonData.NgApCause = &models.NgApCause{}

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(reqData.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(reqData, openapi.MultipartRelatedBinding{})
	}
	if err != nil {
		rlogger.Trace(types.ModuleSmfSbi, rlogger.ERROR, nil, "failed to Unmarshal, error(%s)", err)
		log.Print(err)
		return
	}

	req := sbicmn.NewRequest(c.Request, reqData)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	message := sbicmn.NewSbiHandlerMsg(sbicmn.PduSessReleaseSMContextReq, req)

	//set sc instance id
	message.ScInstId = 0 //todo

	//send to sc process
	sbismf.SendScMsg(message)

	//wait for the response message here
	sbimsg, _ := message.MsgData.(*sbicmn.SbiHandlerMessage)

	rsp := <-sbimsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	if HTTPResponse.Status < 300 {
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	} else {
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}
}

// RetrieveSmContext - Retrieve SM Context
func RetrieveSmContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateSmContext - Update SM Context
func UpdateSmContext(c *gin.Context) {
	rlogger.FuncEntry(types.ModuleSmfSbi, nil)

	//var request models.UpdateSmContextRequest
	reqData := sbicmn.NewUpdateSmContextRequest()

	s := strings.Split(c.GetHeader("Content-Type"), ";")
	var err error
	switch s[0] {
	case "application/json":
		err = c.ShouldBindJSON(reqData.JsonData)
	case "multipart/related":
		err = c.ShouldBindWith(reqData, openapi.MultipartRelatedBinding{})
	}
	if err != nil {
		log.Print(err)
		return
	}

	//for debug:
	rlogger.Trace(types.ModuleSmfSbi, rlogger.DEBUG, nil, "upctxtstat(%v)", reqData.BinaryDataN1SmMessage)

	req := sbicmn.NewRequest(c.Request, reqData)
	req.Params["smContextRef"] = c.Params.ByName("smContextRef")

	message := sbicmn.NewSbiHandlerMsg(sbicmn.PduSessUpdateSMContextReq, req)

	//set sc instance id
	message.ScInstId = 0 //todo

	//send to sc process
	sbismf.SendScMsg(message)

	//wait for the response message here
	sbimsg, _ := message.MsgData.(*sbicmn.SbiHandlerMessage)

	rsp := <-sbimsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	if HTTPResponse.Status < 300 {
		c.Render(HTTPResponse.Status, openapi.MultipartRelatedRender{Data: HTTPResponse.Body})
	} else {
		c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	}
}
