/*
 * NudmUEAU
 *
 * UDM UE Authentication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEAuthentication

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/sbicmn"
	"lite5gc/openapi/models"
	udmhdl "lite5gc/udm/sbi/handler"
)

// GenerateAuthData - Generate authentication data for the UE
func GenerateAuthData(c *gin.Context) {
	var authInfoReq models.AuthenticationInfoRequest
	err := c.ShouldBindJSON(&authInfoReq)
	if err != nil {
		//rlogger.UeauLog.Errorln(err)
	}
	req := sbicmn.NewRequest(c.Request, authInfoReq)
	req.Params["supiOrSuci"] = c.Param("supiOrSuci")

	HTTPResponse := udmhdl.HandleGenerateAuthData(req)

	///*handlerMsg := udm_message.NewHandlerMessage(udm_message.EventGenerateAuthData, req)
	//udm_handler.SendMessage(handlerMsg)
	//rsp := <-handlerMsg.ResponseChan
	//
	//HTTPResponse := rsp.HTTPResponse*/

	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	return
}
