/*
 * NudmUEAU
 *
 * UDM UE Authentication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEAuthentication

import (
	"github.com/gin-gonic/gin"
	"lite5gc/cmn/sbicmn"
	"lite5gc/openapi/http_wrapper"
	"lite5gc/openapi/models"
	"net/http"
)

// ConfirmAuth - Create a new confirmation event
func ConfirmAuth(c *gin.Context) {
	var authEvent models.AuthEvent
	err := c.ShouldBindJSON(&authEvent)
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := sbicmn.NewRequest(c.Request, authEvent)
	req.Params["supi"] = c.Params.ByName("supi")

	//handlerMsg := udm_message.NewHandlerMessage(udm_message.EventConfirmAuth, req)
	//udm_handler.SendMessage(handlerMsg)
	//rsp := <-handlerMsg.ResponseChan
	// ToDo
	HTTPResponse := http_wrapper.Response{}
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
